name: Publicar Reporte de Cobertura

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar PHP y dependencias
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Instalar dependencias con Composer
      run: composer install

    - name: Ejecutar PHPUnit con cobertura
      run: |
        mkdir -p coverage
        vendor/bin/phpunit --coverage-html coverage/

    - name: Deploy a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage
