name: Infection Mutation Testing

on:
  push:
    branches: [main]

jobs:
  infection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP, Composer y extensiones
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, dom, curl
          coverage: xdebug

      - name: Instalar dependencias
        run: composer install

      - name: Ejecutar pruebas con cobertura
        run: |
          vendor/bin/phpunit --coverage-xml=coverage
          vendor/bin/infection --threads=4 --min-msi=70 --min-covered-msi=70 --log-verbosity=all

      - name: Subir reporte a GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
